
/*  getch.c was generated by yup.py (yupp) 0.8b2
    out of getch.yu-c at 2015-03-06 14:47
 *//**
 *  \file  getch.c (getch.yu-c)
 *  \brief  Read from debug interface.
 *  \author  Vitaly Kravtsov (in4lio@gmail.com)
 *  \copyright  See the LICENSE file.
 */

#define LOGGING

#define LINK_CONSOLE

#define LINK_UT

#define LINK_UT_UT

#define LINK_UT_CORO

#define LINK_UT_DATA

#define GETCH_IMPLEMENT

#include "include.h"

/**
 *  \addtogroup char
 *  \{
 */

void getch_init( void )
{
}

void getch_uninit( void )
{
}

__inline int getch_1( void )
{
	return ( kbhit() ? getch() : EOF );
}

__inline bool getch_esc( int chr )
{
	return ( chr == 0 );
}

/** \} */
