
/*  app.h was generated by yup.py (yupp) 1.0c2
    out of app.yu-h 
 *//**
 *  \file  app.h (app.yu-h)
 *  \brief  Application.
 *  \author  Vitaly Kravtsov (in4lio@gmail.com)
 *  \copyright  See the LICENSE file.
 */

#define LOGGING
#define LINK_CONSOLE

#define LINK_UT

#define LINK_UT_UT
#define LINK_UT_CORO
#define LINK_UT_DATA

#ifndef APP_H
#define APP_H

#ifdef  APP_IMPLEMENT
#define APP_EXT
#define APP_INIT( ... ) \
	= __VA_ARGS__

#ifdef __cplusplus
#define APP_EXT_C \
	extern "C"
#else
#define APP_EXT_C \
	extern
#endif

#define APP_VAR( decl ) \
	decl
#define APP_VAR_INIT( decl, ... ) \
	decl = __VA_ARGS__

#ifdef __cplusplus
#define APP_VAR_C( decl ) \
	extern "C" decl; decl
#define APP_VAR_C_INIT( decl, ... ) \
	extern "C" decl; decl = __VA_ARGS__
#else
#define APP_VAR_C( decl ) \
	decl
#define APP_VAR_C_INIT( decl, ... ) \
	decl = __VA_ARGS__
#endif

#define APP_INL

#else  /* APP_IMPLEMENT */
#define APP_EXT \
	extern
#define APP_INIT( ... )

#ifdef __cplusplus
#define APP_EXT_C \
	extern "C"
#else
#define APP_EXT_C \
	extern
#endif

#define APP_VAR( decl ) \
	extern decl
#define APP_VAR_INIT( decl, ... ) \
	extern decl

#ifdef __cplusplus
#define APP_VAR_C( decl ) \
	extern "C" decl
#define APP_VAR_C_INIT( decl, ... ) \
	extern "C" decl
#else
#define APP_VAR_C( decl ) \
	extern decl
#define APP_VAR_C_INIT( decl, ... ) \
	extern decl
#endif

#if __GNUC__ && !__GNUC_STDC_INLINE__
#define APP_INL \
	extern inline
#else
#define APP_INL \
	inline
#endif

#endif /* APP_IMPLEMENT */

/**
 *  \defgroup app Application
 *  \{
 */

/**
 *  \brief Show-must-go-on flag.
 */
APP_VAR_C( int app_alive );

/**
 *  \brief Application exit status.
 */
APP_VAR_C_INIT( int app_return, 0 );

/**
 *  \brief Initialize application.
 */
APP_EXT_C int app_init( int argc, char *argv[]);

/**
 *  \brief Uninitialize application.
 */
APP_EXT_C void app_uninit( void );

/**
 *  \brief Debug interface title message.
 *  \hideinitializer
 */
;
/** \} */

#undef APP_EXT
#undef APP_INIT
#undef APP_EXT_C
#undef APP_VAR
#undef APP_VAR_INIT
#undef APP_VAR_C
#undef APP_VAR_C_INIT
#undef APP_INL
#endif

