
/*  config.h was generated by yup.py (yupp) 1.0b6
    out of config.yu-h 
 *//**
 *  \file  config.h (config.yu-h)
 *  \brief  Configuration.
 *  \author  Vitaly Kravtsov (in4lio@gmail.com)
 *  \copyright  See the LICENSE file.
 */

#ifndef CONFIG_H
#define CONFIG_H

#ifdef  CONFIG_IMPLEMENT
#define CONFIG_EXT
#define CONFIG_EXT_INIT( dec, init ) \
	dec = init
#define CONFIG_EXT_C
#define CONFIG_EXT_C_INIT( dec, init ) \
	dec = init
#define CONFIG_INL
#else
#define CONFIG_EXT extern
#define CONFIG_EXT_INIT( dec, init ) \
	extern dec
#ifdef __cplusplus
#define CONFIG_C "C"
#else
#define CONFIG_C
#endif
#define CONFIG_EXT_C extern CONFIG_C
#define CONFIG_EXT_C_INIT( dec, init ) \
	extern CONFIG_C dec
#if __GNUC__ && !__GNUC_STDC_INLINE__
#define CONFIG_INL extern inline
#else
#define CONFIG_INL inline
#endif
#endif

#ifndef COMMA
#define COMMA ,
#endif

/**
 *  \defgroup config Configuration
 *  \ingroup app
 *  \{
 */

#define LOGGING
#define LINK_CONSOLE

#define LINK_UT

#define LINK_UT_UT
#define LINK_UT_CORO
#define LINK_UT_DATA

/** \} */

#undef CONFIG_EXT
#undef CONFIG_EXT_INIT
#undef CONFIG_EXT_C
#undef CONFIG_EXT_C_INIT
#undef CONFIG_INL
#undef CONFIG_C
#endif

