
/*  config.h was generated by yup.py (yupp) 1.0c2
    out of config.yu-h 
 *//**
 *  \file  config.h (config.yu-h)
 *  \brief  Configuration.
 *  \author  Vitaly Kravtsov (in4lio@gmail.com)
 *  \copyright  See the LICENSE file.
 */

/**
 *  \defgroup config Configuration
 *  \ingroup app
 *  \{
 */

#define LOGGING
#define LINK_CONSOLE

#define LINK_UT

#define LINK_UT_UT
#define LINK_UT_CORO
#define LINK_UT_DATA

/** \} */
