
/*  data-str.h was generated by yup.py (yupp) 0.8b2
    out of data-str.yu-h at 2015-04-14 13:48
 *//**
 *  \file  data-str.h (data-str.yu-h)
 *  \brief  String converting.
 *  \author  Vitaly Kravtsov (in4lio@gmail.com)
 *  \copyright  See the LICENSE file.
 */

#define LOGGING

#define LINK_CONSOLE

#define LINK_UT

#define LINK_UT_UT

#define LINK_UT_CORO

#define LINK_UT_DATA

#ifndef DATA_STR_H
#define DATA_STR_H

#ifdef  DATA_STR_IMPLEMENT
#define DATA_STR_EXT
#define DATA_STR_EXT_INIT( dec, init ) \
	dec = init
#else
#define DATA_STR_EXT extern
#define DATA_STR_EXT_INIT( dec, init ) \
	extern dec
#endif

#ifndef COMMA
#define COMMA   ,
#endif

#ifdef __cplusplus
extern "C" {
#endif

/**
 *  \addtogroup data
 *  \{
 */

#define __strtol( s, end )    strtol( s, end, 0 )
#define __strtoul( s, end )   strtoul( s, end, 0 )
#define __strtoll( s, end )   strtoll( s, end, 0 )
#define __strtoull( s, end )  strtoull( s, end, 0 )
#define __strtof( s, end )    (( float ) strtod( s, end ))

/**
 *  \brief byte-to-hex converting.
 *  \param s String buffer.
 *  \param val Value.
 *  \return String.
 */
DATA_STR_EXT char *string_byte_h( char *s, byte val );

/**
 *  \brief word-to-hex converting.
 *  \param s String buffer.
 *  \param val Value.
 *  \return String.
 */
DATA_STR_EXT char *string_word_h( char *s, word val );

/**
 *  \brief dword-to-hex converting.
 *  \param s String buffer.
 *  \param val Value.
 *  \return String.
 */
DATA_STR_EXT char *string_dword_h( char *s, dword val );

/** \} */

#ifdef __cplusplus
}
#endif

#endif

