
/*  ini.c was generated by yup.py (yupp) 0.9b4
    out of ini.yu-c 
 *//**
 *  \file  ini.c (ini.yu-c)
 *  \brief  Configuration options.
 *  \author  Vitaly Kravtsov (in4lio@gmail.com)
 *  \copyright  See the LICENSE file.
 */

#define LOGGING
#define LINK_CONSOLE

#define LINK_UT

#define LINK_UT_UT
#define LINK_UT_CORO
#define LINK_UT_DATA

#define INI_IMPLEMENT

#include "include.h"

#define __SEC  "predict"

bool ini_set_file( char *fn )
{
// CORTEX_M //////////////////////////////////////
#if defined( __ARM_ARCH )

	return ( false );

// UNIX //////////////////////////////////////////
// WIN32 /////////////////////////////////////////
// MSDOS /////////////////////////////////////////
#else
	FILE *f;

	f = fopen( fn, "r" );
	if ( f == NULL ) {
		ERROR( file_open, fn, strerror( errno ));
		return ( false );
	}
	fclose( f );
	ini_path = fn;
	printf( __CRLF__"Configure file: %s", ini_path );
	return ( true );

//////////////////////////////////////////////////
#endif
}

void ini_load( void )
{

#if __NOT_IMPLEMENTED__
	set_config_file( ini_path );

	ini_cyclic_delay = get_config_int( __SEC, "cyclic_delay", ini_cyclic_delay );
	ini_data_prot = get_config_bool( __SEC, "data_prot", ini_data_prot );
	ini_data_prot_filter = get_config_char( __SEC, "data_prot_filter", ini_data_prot_filter );
	ini_data_prot_filter_skip = get_config_char( __SEC, "data_prot_filter_skip", ini_data_prot_filter_skip );
	ini_log_path = get_config_char( __SEC, "log_path", ini_log_path );
	ini_log_level = get_config_int( __SEC, "log_level", ini_log_level );

#endif
}

void ini_save( void )
{

#if __NOT_IMPLEMENTED__
	set_config_file( ini_path );

	set_config_int( __SEC, "cyclic_delay", ini_cyclic_delay );
	set_config_bool( __SEC, "data_prot", ini_data_prot );
	set_config_char( __SEC, "data_prot_filter", ini_data_prot_filter );
	set_config_char( __SEC, "data_prot_filter_skip", ini_data_prot_filter_skip );
	set_config_char( __SEC, "log_path", ini_log_path );
	set_config_int( __SEC, "log_level", ini_log_level );

	flush_config_file();

#endif
}
