
/*  ini.h was generated by yup.py (yupp) 1.0c2
    out of ini.yu-h 
 *//**
 *  \file  ini.h (ini.yu-h)
 *  \brief  Configuration options.
 *  \author  Vitaly Kravtsov (in4lio@gmail.com)
 *  \copyright  See the LICENSE file.
 */

#define LOGGING
#define LINK_CONSOLE

#define LINK_UT

#define LINK_UT_UT
#define LINK_UT_CORO
#define LINK_UT_DATA

#ifndef INI_H
#define INI_H

#ifdef  INI_IMPLEMENT
#define INI_EXT
#define INI_INIT( ... ) \
	= __VA_ARGS__

#ifdef __cplusplus
#define INI_EXT_C \
	extern "C"
#else
#define INI_EXT_C \
	extern
#endif

#define INI_VAR( decl ) \
	decl
#define INI_VAR_INIT( decl, ... ) \
	decl = __VA_ARGS__

#ifdef __cplusplus
#define INI_VAR_C( decl ) \
	extern "C" decl; decl
#define INI_VAR_C_INIT( decl, ... ) \
	extern "C" decl; decl = __VA_ARGS__
#else
#define INI_VAR_C( decl ) \
	decl
#define INI_VAR_C_INIT( decl, ... ) \
	decl = __VA_ARGS__
#endif

#define INI_INL

#else  /* INI_IMPLEMENT */
#define INI_EXT \
	extern
#define INI_INIT( ... )

#ifdef __cplusplus
#define INI_EXT_C \
	extern "C"
#else
#define INI_EXT_C \
	extern
#endif

#define INI_VAR( decl ) \
	extern decl
#define INI_VAR_INIT( decl, ... ) \
	extern decl

#ifdef __cplusplus
#define INI_VAR_C( decl ) \
	extern "C" decl
#define INI_VAR_C_INIT( decl, ... ) \
	extern "C" decl
#else
#define INI_VAR_C( decl ) \
	extern decl
#define INI_VAR_C_INIT( decl, ... ) \
	extern decl
#endif

#if __GNUC__ && !__GNUC_STDC_INLINE__
#define INI_INL \
	extern inline
#else
#define INI_INL \
	inline
#endif

#endif /* INI_IMPLEMENT */

/**
 *  \defgroup ini Configuration options
 *  \ingroup core
 *  \{
 */

/**
 *  \page ini Configuration options
 *
 *  \section i_cyclic_delay cyclic_delay
 *  Interval of cyclic command execution (seconds).
 *
 *  \section i_data_prot data_prot
 *  Display protocol of state changing (flag).
 *
 *  \section i_data_prot_filter data_prot_filter
 *  Protocol displaying filter (substring is contained in variable name).
 *
 *  \section i_data_prot_filter_skip data_prot_filter_skip
 *  Protocol displaying filter (substring is absent in variable name).
 *
 *  \section i_log_path log_path
 *  Log-file name.
 *
 *  \section i_log_level log_level
 *  Logging level.
 */

INI_VAR_C_INIT( int ini_cyclic_delay, 5 );
INI_VAR_C_INIT( bool ini_data_prot, false );
INI_VAR_C_INIT( char ini_data_prot_filter[ 128 ], "" );
INI_VAR_C_INIT( char ini_data_prot_filter_skip[ 128 ], "_ut_" );
INI_VAR_C_INIT( char ini_log_path[ 64 ], "predict.log" );
INI_VAR_C_INIT( int ini_log_level, LOG_LEVEL_ERROR );

/**
 *  \brief Configuration file name.
 */
INI_VAR_C_INIT( char *ini_path, "./predict.cfg" );

INI_EXT_C bool ini_set_file( char *fn );

INI_EXT_C void ini_load( void );

INI_EXT_C void ini_save( void );

/** \} */

#undef INI_EXT
#undef INI_INIT
#undef INI_EXT_C
#undef INI_VAR
#undef INI_VAR_INIT
#undef INI_VAR_C
#undef INI_VAR_C_INIT
#undef INI_INL
#endif

