
/*  console.h was generated by yup.py (yupp) 0.8b2
    out of console.yu-h at 2015-04-14 13:48
 *//**
 *  \file  console.h (console.yu-h)
 *  \brief  Debug console.
 *  \author  Vitaly Kravtsov (in4lio@gmail.com)
 *  \copyright  See the LICENSE file.
 */

#define LOGGING

#define LINK_CONSOLE

#define LINK_UT

#define LINK_UT_UT

#define LINK_UT_CORO

#define LINK_UT_DATA

#ifndef CONSOLE_H
#define CONSOLE_H

#ifdef  CONSOLE_IMPLEMENT
#define CONSOLE_EXT
#define CONSOLE_EXT_INIT( dec, init ) \
	dec = init
#else
#define CONSOLE_EXT extern
#define CONSOLE_EXT_INIT( dec, init ) \
	extern dec
#endif

#ifndef COMMA
#define COMMA   ,
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef LINK_CONSOLE

/**
 *  \defgroup console Debug console.
 *  \ingroup core
 *
 *	Structure of <b>console-dict.yu</b> file:
 *
 *  <b>CONSOLE_CMD</b> - Dictionary of console commands.
 *  \param CONSOLE_CMD Console command.
 *  \param CMD_PAR_N Command parameters count.
 *  \param CMD_CYCLIC Cyclic command flag.
 *  \{
 */

/**
 *  \brief Command line prompt.
 *  \hideinitializer
 */
#define CONSOLE_PROMPT       "$"

/**
 *  \brief Command line prompt in case of selecting command from list.
 *  \hideinitializer
 */
#define CONSOLE_PROMPT_LIST  "#"

/**
 *  \brief Print message about function call.
 *  \param FORMAT Message format.
 *  \param ... Message arguments.
 *  \hideinitializer
 */
#define __echo_call( FORMAT, ... ) __echo( "CALL", FORMAT, ## __VA_ARGS__ )

/**
 *  \brief Print debug message.
 *  \param FORMAT Message format.
 *  \param ... Message arguments.
 *  \hideinitializer
 */
#define __echo_debug( FORMAT, ... ) __echo( "INFO", FORMAT, ## __VA_ARGS__ )

/**
 *  \brief Print warning.
 *  \param FORMAT Message format.
 *  \param ... Message arguments.
 *  \hideinitializer
 */
#define __echo_warn( FORMAT, ... ) do { \
	__echo( "WARN", ); \
	printf( FORMAT, ## __VA_ARGS__ ); \
	flush(); \
} while ( 0 )

/**
 *  \brief Print error.
 *  \param FORMAT Message format.
 *  \param err Error number.
 *  \param ... Message arguments.
 *  \hideinitializer
 */
#define __echo_error( FORMAT, err, ... ) do { \
	__echo( "ERROR #%X", COMMA err ); \
	printf( FORMAT, ## __VA_ARGS__ ); \
	flush(); \
} while ( 0 )

/**
 *  \page console Console commands
 *
 *  \section c_delay c_delay
 *  Interval of cyclic command execution.
 *
 *  \section c_data data
 *  Application state-space representation.
 *  \code
 *  data s -s
 *  s     - filter: substring (s) is contained in variable name
 *  -s    - filter: substring (s) is absent in variable name
 *  \endcode
 *
 *  \section c_d_flt d_flt
 *  Filter of state changing protocol.
 *  \code
 *  d_flt s -s * -
 *  s     - substring (s) is contained in variable name
 *  -s    - substring (s) is absent in variable name
 *  *     - reset "substring is contained" filter
 *  -     - reset "substring is absent" filter
 *  \endcode
 *
 *  \section c_d_get d_get
 *  Get value of state variable.
 *
 *  \section c_d_list d_list
 *  List of state variables, see \ref c_data "data".
 *  \code
 *  d_list s -s
 *  \endcode
 *
 *  \section c_d_prot d_prot
 *  Display state changing protocol.
 *
 *  \section c_d_set d_set
 *  Set value of state variable.
 *
 *  \section c_help help
 *  List of console commands.
 *
 *  \section c_ini ini
 *  Save program settings.
 *
 *  \section c_quit quit
 *  Quit program.
 *
 *  \section c_stop stop
 *  Stop cyclic command execution.
 *
 *  \section c_time time
 *  Current time.
 *  \code
 *  time 1
 *  1     - display once;
 *  \endcode
 *
 *  \section c_ut ut
 *  Restart unit testing of 2nd stage.
 *
 *  \section c_u_result u_result
 *  Unit testing result.
 *
 *  \section c_version version
 *  Program version.
 */

/**
 *  \brief Console commands count.
 */
#define CONSOLE_COMMAND_COUNT  (15 + 1 )

/**
 *  \brief List of console commands.
 */
CONSOLE_EXT const char * const console_command[];

/**
 *  \brief Index of selected from list command.
 */
CONSOLE_EXT int console_index;

#define cyclic_delay_MIN  1
#define cyclic_delay_MAX  600

/**
 *  \brief Print prompt.
 */
CONSOLE_EXT void console_prompt( void );

/**
 *  \brief Check console is waiting for command.
 */
CONSOLE_EXT bool console_command_waited( void );

/** \} */

#else /* LINK_CONSOLE */

#define __echo( PRE, FORMAT, ... ) NULL
#define __echo_call( FORMAT, ... ) NULL
#define __echo_debug( FORMAT, ... ) NULL
#define __echo_warn( FORMAT, ... ) NULL
#define __echo_error( FORMAT, err, ... ) NULL

#endif /* LINK_CONSOLE */

#ifdef __cplusplus
}
#endif

#endif

