
/*  getch.h was generated by yup.py (yupp) 1.0b6
    out of getch.yu-h 
 *//**
 *  \file  getch.h (getch.yu-h)
 *  \brief  Read from debug interface.
 *  \author  Vitaly Kravtsov (in4lio@gmail.com)
 *  \copyright  See the LICENSE file.
 */

#define LOGGING
#define LINK_CONSOLE

#define LINK_UT

#define LINK_UT_UT
#define LINK_UT_CORO
#define LINK_UT_DATA

#ifndef GETCH_H
#define GETCH_H

#ifdef  GETCH_IMPLEMENT
#define GETCH_EXT
#define GETCH_EXT_INIT( dec, init ) \
	dec = init
#define GETCH_EXT_C
#define GETCH_EXT_C_INIT( dec, init ) \
	dec = init
#define GETCH_INL
#else
#define GETCH_EXT extern
#define GETCH_EXT_INIT( dec, init ) \
	extern dec
#ifdef __cplusplus
#define GETCH_C "C"
#else
#define GETCH_C
#endif
#define GETCH_EXT_C extern GETCH_C
#define GETCH_EXT_C_INIT( dec, init ) \
	extern GETCH_C dec
#if __GNUC__ && !__GNUC_STDC_INLINE__
#define GETCH_INL extern inline
#else
#define GETCH_INL inline
#endif
#endif

#ifndef COMMA
#define COMMA ,
#endif

#ifdef LINK_CONSOLE

#include <conio.h>

/**
 *  \addtogroup char
 *  \{
 */

GETCH_EXT_C void getch_init( void );
GETCH_EXT_C void getch_uninit( void );
GETCH_EXT_C int getch_1( void );
GETCH_EXT_C int getch_escseq( int chr );

/** \} */

#endif /* LINK_CONSOLE */

/**
 *  \defgroup char_char Characters definitions
 *  \ingroup char
 *  \{
 */

#define CHAR_TAB        '\x09'
#define CHAR_LF         '\x0A'
#define CHAR_CR         '\x0D'
#define CHAR_ESC        '\x1B'
#define CHAR_SPACE      '\x20'
#define LAST_CHAR       '\x7E'  /**< Last character to be displayed. */
#define CHAR_BACKSPACE  '\x08'
#define CHAR_UP         '\x48'
#define CHAR_DOWN       '\x50'
#define CHAR_RIGHT      '\x4D'
#define CHAR_LEFT       '\x4B'
#define CHAR_ENTER      CHAR_CR
#define __CRLF__        "\x0A"

/** \} */

#undef GETCH_EXT
#undef GETCH_EXT_INIT
#undef GETCH_EXT_C
#undef GETCH_EXT_C_INIT
#undef GETCH_INL
#undef GETCH_C
#endif

