
/*  getch.h was generated by yup.py (yupp) 1.0c2
    out of getch.yu-h 
 *//**
 *  \file  getch.h (getch.yu-h)
 *  \brief  Read from debug interface.
 *  \author  Vitaly Kravtsov (in4lio@gmail.com)
 *  \copyright  See the LICENSE file.
 */

#define LOGGING
#define LINK_CONSOLE

#define LINK_UT

#define LINK_UT_UT
#define LINK_UT_CORO
#define LINK_UT_DATA

#ifndef GETCH_H
#define GETCH_H

#ifdef  GETCH_IMPLEMENT
#define GETCH_EXT
#define GETCH_INIT( ... ) \
	= __VA_ARGS__

#ifdef __cplusplus
#define GETCH_EXT_C \
	extern "C"
#else
#define GETCH_EXT_C \
	extern
#endif

#define GETCH_VAR( decl ) \
	decl
#define GETCH_VAR_INIT( decl, ... ) \
	decl = __VA_ARGS__

#ifdef __cplusplus
#define GETCH_VAR_C( decl ) \
	extern "C" decl; decl
#define GETCH_VAR_C_INIT( decl, ... ) \
	extern "C" decl; decl = __VA_ARGS__
#else
#define GETCH_VAR_C( decl ) \
	decl
#define GETCH_VAR_C_INIT( decl, ... ) \
	decl = __VA_ARGS__
#endif

#define GETCH_INL

#else  /* GETCH_IMPLEMENT */
#define GETCH_EXT \
	extern
#define GETCH_INIT( ... )

#ifdef __cplusplus
#define GETCH_EXT_C \
	extern "C"
#else
#define GETCH_EXT_C \
	extern
#endif

#define GETCH_VAR( decl ) \
	extern decl
#define GETCH_VAR_INIT( decl, ... ) \
	extern decl

#ifdef __cplusplus
#define GETCH_VAR_C( decl ) \
	extern "C" decl
#define GETCH_VAR_C_INIT( decl, ... ) \
	extern "C" decl
#else
#define GETCH_VAR_C( decl ) \
	extern decl
#define GETCH_VAR_C_INIT( decl, ... ) \
	extern decl
#endif

#if __GNUC__ && !__GNUC_STDC_INLINE__
#define GETCH_INL \
	extern inline
#else
#define GETCH_INL \
	inline
#endif

#endif /* GETCH_IMPLEMENT */

#ifdef LINK_CONSOLE

#include <conio.h>

/**
 *  \addtogroup char
 *  \{
 */

GETCH_EXT_C void getch_init( void );
GETCH_EXT_C void getch_uninit( void );
GETCH_EXT_C int getch_1( void );
GETCH_EXT_C int getch_escseq( int chr );

/** \} */

#endif /* LINK_CONSOLE */

/**
 *  \defgroup char_char Characters definitions
 *  \ingroup char
 *  \{
 */

#define CHAR_TAB        '\x09'
#define CHAR_LF         '\x0A'
#define CHAR_CR         '\x0D'
#define CHAR_ESC        '\x1B'
#define CHAR_SPACE      '\x20'
#define LAST_CHAR       '\x7E'  /**< Last character to be displayed. */
#define CHAR_BACKSPACE  '\x08'
#define CHAR_UP         '\x48'
#define CHAR_DOWN       '\x50'
#define CHAR_RIGHT      '\x4D'
#define CHAR_LEFT       '\x4B'
#define CHAR_ENTER      CHAR_CR
#define __CRLF__        "\x0A"

/** \} */

#undef GETCH_EXT
#undef GETCH_INIT
#undef GETCH_EXT_C
#undef GETCH_VAR
#undef GETCH_VAR_INIT
#undef GETCH_VAR_C
#undef GETCH_VAR_C_INIT
#undef GETCH_INL
#endif

